/* 138 - try cacth */

const numero1 = 20, numero3 = 30

console.log(numero1);

try {
    console.log(numero2);
} catch (error) {
    console.log(error);

}

console.log(numero3);
